# Generated by Django 5.1.5 on 2025-01-22 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameImgIdModel',
            fields=[
                ('nmID', models.CharField(default='0', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('img_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IdSizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizes', models.CharField(max_length=20)),
                ('nmID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nameimgidmodel')),
            ],
        ),
    ]
