# Generated by Django 5.1.5 on 2025-01-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nameimgidmodel',
            old_name='img_url',
            new_name='photos',
        ),
        migrations.RenameField(
            model_name='nameimgidmodel',
            old_name='name',
            new_name='vendorCode',
        ),
    ]
