# Generated by Django 5.1.5 on 2025-01-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_img_url_nameimgidmodel_photos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTable',
            fields=[
                ('date', models.DateTimeField()),
                ('supplierArticle', models.CharField(max_length=100)),
                ('nmId', models.CharField(max_length=30)),
                ('techSize', models.CharField(max_length=50)),
                ('priceWithDisc', models.CharField(max_length=30)),
                ('saleID', models.CharField(default='0', max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
