# Generated by Django 5.1.5 on 2025-01-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_salestable'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersTable',
            fields=[
                ('srid', models.CharField(default='0', max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('warehouseName', models.CharField(max_length=30)),
                ('oblastOkrugName', models.CharField(max_length=50)),
                ('regionName', models.CharField(max_length=50)),
                ('supplierArticle', models.CharField(max_length=100)),
                ('nmId', models.CharField(max_length=30)),
                ('barcode', models.CharField(max_length=30)),
                ('incomeID', models.CharField(max_length=30)),
                ('finishedPrice', models.CharField(max_length=30)),
                ('priceWithDisc', models.CharField(max_length=30)),
                ('isCancel', models.CharField(default='0', max_length=10)),
            ],
        ),
    ]
